name: Release
on: push
jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 15
      - name: Install Yarn
        run: npm install --global yarn
      - name: Install dependencies
        run: yarn
      - name: Publish release
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
